import { PrismaClient, PreferredLanguage, AccountStatus, MaterialCategory, PriceSource, RecyclerAuthorizationStatus, PickupAvailability } from '@prisma/client';
import { scryptSync } from 'node:crypto';
const prisma = new PrismaClient();
const demoPasswordHash = `${Buffer.from('kabadiwala-demo-salt').toString('hex')}:${scryptSync('DemoPass123!', Buffer.from('kabadiwala-demo-salt'), 64).toString('hex')}`;
async function main() {
  const demoCollector = await prisma.collector.upsert({ where: { phone: '9876543210' }, update: { email: 'dev-collector@kabadiwala.example' }, create: { phone: '9876543210', email: 'dev-collector@kabadiwala.example', preferredLanguage: PreferredLanguage.HINDI, areaName: 'Development Area', accountStatus: AccountStatus.ACTIVE } });
  await prisma.user.upsert({ where: { email: 'dev-collector@kabadiwala.example' }, update: { collectorProfileId: demoCollector.id, role: 'COLLECTOR', preferredLanguage: PreferredLanguage.HINDI, accountStatus: AccountStatus.ACTIVE }, create: { email: 'dev-collector@kabadiwala.example', passwordHash: demoPasswordHash, role: 'COLLECTOR', preferredLanguage: PreferredLanguage.HINDI, collectorProfileId: demoCollector.id, accountStatus: AccountStatus.ACTIVE } });
  const rows = [{ id: 'dev-mumbai-pcb', materialCategory: MaterialCategory.PCB, city: 'Mumbai', priceMin: 2200, priceMax: 2800, marketPrice: 2500 }, { id: 'dev-mumbai-cable', materialCategory: MaterialCategory.CABLE, city: 'Mumbai', priceMin: 500, priceMax: 700, marketPrice: 600 }, { id: 'dev-pune-pcb', materialCategory: MaterialCategory.PCB, city: 'Pune', priceMin: 2100, priceMax: 2700, marketPrice: 2400 }];
  for (const row of rows) { const effectiveAt = new Date(); const { id, ...values } = row; const price = await prisma.price.upsert({ where: { id }, update: { ...values, source: PriceSource.SYSTEM, effectiveAt }, create: { id, ...values, source: PriceSource.SYSTEM, effectiveAt, historicalAverage: row.marketPrice } }); for (let i = 3; i >= 0; i--) { const marketPrice = row.marketPrice - i * 25; await prisma.priceHistory.upsert({ where: { id: `${row.id}-h${i}` }, update: { marketPrice, effectiveAt: new Date(Date.now() - i * 7 * 86400000) }, create: { id: `${row.id}-h${i}`, priceId: price.id, materialCategory: row.materialCategory, city: row.city, priceMin: row.priceMin, priceMax: row.priceMax, marketPrice, source: PriceSource.SYSTEM, effectiveAt: new Date(Date.now() - i * 7 * 86400000) } }); } }
  await prisma.rewardProgram.upsert({ where: { programKey: 'monthly-collector-25kg' }, update: { active: true, title: 'Monthly collection bonus', description: 'Complete 25 kg of verified paid handovers this month to unlock a platform bonus.', rewardType: 'CASH_BONUS', thresholdKg: 25, thresholdRupees: null, rewardAmount: 150, terms: 'Applies once per calendar month after a verified paid handover.', startsAt: new Date('2025-01-01T00:00:00.000Z') }, create: { programKey: 'monthly-collector-25kg', title: 'Monthly collection bonus', description: 'Complete 25 kg of verified paid handovers this month to unlock a platform bonus.', rewardType: 'CASH_BONUS', thresholdKg: 25, rewardAmount: 150, terms: 'Applies once per calendar month after a verified paid handover.', startsAt: new Date('2025-01-01T00:00:00.000Z') } });
  await prisma.governmentScheme.upsert({ where: { slug: 'pm-svanidhi-guidance' }, update: { active: true, lastVerifiedAt: new Date() }, create: { slug: 'pm-svanidhi-guidance', title: 'Small business support guidance', description: 'A guided checklist for informal workers exploring official small-business support. Verify details with the government source before applying.', eligibilityRules: { workType: ['COLLECTOR', 'RECYCLER'] }, requiredDocuments: ['Identity proof', 'Bank account details', 'Address proof'], sourceUrl: 'https://www.myscheme.gov.in/', lastVerifiedAt: new Date(), supportedLanguages: ['en', 'hi', 'mr'], active: true } });
  await prisma.diyActivity.upsert({ where: { slug: 'cable-organizer' }, update: { active: true }, create: { slug: 'cable-organizer', title: 'Cable organiser', description: 'Turn safe, unplugged cable lengths into a simple organiser for a drawer or work table.', materials: ['Clean insulated cables', 'Cardboard strip', 'Tape'], steps: ['Check that cables are unplugged and have no exposed wire.', 'Bundle short lengths around a cardboard strip.', 'Secure the bundle with tape and label it.'], safetyWarnings: ['Do not use cables with exposed copper.', 'Never cut or open batteries, CRTs, capacitors, or sealed electronics.'], difficulty: 'Easy', minutes: 15, supportedLanguages: ['en', 'hi', 'mr'], active: true } });
  const recyclers=[{id:'dev-recycler-mumbai',name:'Development Recycler Mumbai',areaName:'Mumbai',address:'Development address, Mumbai',latitude:19.076,longitude:72.8777,materials:[MaterialCategory.PCB,MaterialCategory.CABLE],rate:2500,availability:PickupAvailability.TODAY,max:25,rating:4.4},{id:'dev-recycler-pune',name:'Development Recycler Pune',areaName:'Pune',address:'Development address, Pune',latitude:18.5204,longitude:73.8567,materials:[MaterialCategory.PCB],rate:2350,availability:PickupAvailability.THIS_WEEK,max:50,rating:null},{id:'dev-recycler-pending',name:'Development Pending Recycler',areaName:'Mumbai',address:'Development address, Mumbai',latitude:19.1,longitude:72.9,materials:[MaterialCategory.PCB],rate:2800,availability:PickupAvailability.FLEXIBLE,max:10,rating:null}];
  for(const r of recyclers){const recycler=await prisma.recycler.upsert({where:{id:r.id},update:{name:r.name,areaName:r.areaName,address:r.address,latitude:r.latitude,longitude:r.longitude,authorizationStatus:r.id.endsWith('pending')?RecyclerAuthorizationStatus.PENDING:RecyclerAuthorizationStatus.VERIFIED,pickupAvailability:r.availability,maxPickupDistanceKm:r.max,operatingHours:{monday:{open:'09:00',close:'18:00'}},rating:r.rating,reviewCount:r.rating?12:0},create:{id:r.id,name:r.name,areaName:r.areaName,address:r.address,latitude:r.latitude,longitude:r.longitude,authorizationStatus:r.id.endsWith('pending')?RecyclerAuthorizationStatus.PENDING:RecyclerAuthorizationStatus.VERIFIED,pickupAvailability:r.availability,maxPickupDistanceKm:r.max,operatingHours:{monday:{open:'09:00',close:'18:00'}},rating:r.rating,reviewCount:r.rating?12:0}});await prisma.recyclerMaterial.deleteMany({where:{recyclerId:r.id}});await prisma.recyclerRate.deleteMany({where:{recyclerId:r.id}});for(const m of r.materials)await prisma.recyclerMaterial.create({data:{recyclerId:recycler.id,category:m,subcategories:[],minAcceptableWeight:0.1,maxAcceptableWeight:500}});for(const m of r.materials)await prisma.recyclerRate.create({data:{recyclerId:recycler.id,materialCategory:m,pricePerKg:r.rate}});}
  const verifiedDemoRecycler = await prisma.recycler.findUnique({ where: { id: 'dev-recycler-pune' } });
  if (verifiedDemoRecycler) await prisma.user.upsert({ where: { email: 'dev-recycler@kabadiwala.example' }, update: { recyclerProfileId: verifiedDemoRecycler.id, role: 'RECYCLER', preferredLanguage: PreferredLanguage.ENGLISH, accountStatus: AccountStatus.ACTIVE }, create: { email: 'dev-recycler@kabadiwala.example', passwordHash: demoPasswordHash, role: 'RECYCLER', preferredLanguage: PreferredLanguage.ENGLISH, recyclerProfileId: verifiedDemoRecycler.id, accountStatus: AccountStatus.ACTIVE } });
  console.log('Development collector and price seed complete. Price data is test data, not current market claims.');
}
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
