import type { AppConfig } from '../config/env.js';
import { AppError } from '../utils/errors.js';

export interface OtpProvider { request(phone: string): Promise<void>; verify(phone: string, otp: string): Promise<'approved'|'invalid'|'expired'|'locked'>; }
export class DevelopmentOtpProvider implements OtpProvider { private readonly records = new Map<string, { code: string; expires: number; attempts: number; lockedUntil: number }>(); constructor(private readonly config: AppConfig) {} async request(phone: string) { this.records.set(phone, { code: this.config.DEV_OTP_CODE, expires: Date.now() + 5 * 60_000, attempts: 0, lockedUntil: 0 }); } async verify(phone: string, otp: string) { const record = this.records.get(phone); // Development deployments may run multiple processes, so the in-memory request record can be missing on verify. The configured fixed test code remains the deliberate development fallback.
    if (!record) return otp === this.config.DEV_OTP_CODE ? 'approved' : 'expired';
    if (Date.now() >= record.expires) return 'expired'; if (Date.now() < record.lockedUntil) return 'locked'; if (++record.attempts > 5) { record.lockedUntil = Date.now() + 15 * 60_000; return 'locked'; } if (otp !== record.code) return 'invalid'; this.records.delete(phone); return 'approved'; } }
export class TwilioVerifyProvider implements OtpProvider { constructor(private readonly config: AppConfig) {} private get auth() { return Buffer.from(`${this.config.TWILIO_ACCOUNT_SID}:${this.config.TWILIO_AUTH_TOKEN}`).toString('base64'); } async request(phone: string) { const response = await fetch(`https://verify.twilio.com/v2/Services/${this.config.TWILIO_VERIFY_SERVICE_SID}/Verifications`, { method: 'POST', headers: { Authorization: `Basic ${this.auth}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ To: `+91${phone}`, Channel: 'sms' }) }); if (!response.ok) throw new AppError('INTERNAL_SERVER_ERROR', 'OTP provider unavailable', 502); } async verify(phone: string, otp: string) { const response = await fetch(`https://verify.twilio.com/v2/Services/${this.config.TWILIO_VERIFY_SERVICE_SID}/VerificationCheck`, { method: 'POST', headers: { Authorization: `Basic ${this.auth}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ To: `+91${phone}`, Code: otp }) }); if (response.status === 404) return 'expired'; if (!response.ok) throw new AppError('INTERNAL_SERVER_ERROR', 'OTP provider unavailable', 502); const body = await response.json() as { status?: string }; return body.status === 'approved' ? 'approved' : 'invalid'; } }
export function createOtpProvider(config: AppConfig): OtpProvider { return config.OTP_PROVIDER === 'twilio' ? new TwilioVerifyProvider(config) : new DevelopmentOtpProvider(config); }
