import type { Request, Response } from 'express'; import { phoneSchema } from '../utils/validation.js'; import { AppError } from '../utils/errors.js'; import type { AuthService, PhoneAccountInput } from '../services/authService.js'; import type { EmailAuthService } from '../services/emailAuthService.js'; import { z } from 'zod';
const optionalTrimmed = (max: number) => z.preprocess(value => typeof value === 'string' && value.trim() === '' ? undefined : value, z.string().trim().max(max).optional());
const optionalEmail = z.preprocess(value => typeof value === 'string' && value.trim() === '' ? undefined : value, z.string().trim().email().max(254).optional());
const languageInput = z.enum(['ENGLISH','MARATHI','HINDI','ASSAMESE','BENGALI','BODO','DOGRI','GUJARATI','KANNADA','KASHMIRI','KONKANI','MAITHILI','MALAYALAM','MANIPURI','NEPALI','ODIA','PUNJABI','SANSKRIT','SANTALI','SINDHI','TAMIL','TELUGU','URDU']).default('ENGLISH');
const emailInput = z.object({ email: z.string().trim().email().max(254), password: z.string().min(8).max(128), role: z.enum(['HOUSEHOLD', 'COLLECTOR', 'RECYCLER']), preferredLanguage: languageInput, areaName: optionalTrimmed(160), businessName: optionalTrimmed(160), authorizationNumber: optionalTrimmed(120), materialsAccepted: z.array(z.string().trim().min(1).max(40)).max(20).optional(), pickupAvailable: z.boolean().optional(), serviceRadiusKm: z.number().finite().min(1).max(200).optional() }).superRefine((value, ctx) => {
  if (value.role === 'RECYCLER' && !value.businessName) ctx.addIssue({ code: 'custom', path: ['businessName'], message: 'Business name is required for recycler registration' });
  if (value.role === 'RECYCLER' && !value.materialsAccepted?.length) ctx.addIssue({ code: 'custom', path: ['materialsAccepted'], message: 'At least one accepted material is required for recycler registration' });
});
const phoneAccountInput = z.object({ role: z.enum(['HOUSEHOLD', 'COLLECTOR', 'RECYCLER']).optional(), preferredLanguage: z.string().trim().max(40).optional(), areaName: optionalTrimmed(160), latitude: z.number().finite().min(-90).max(90).optional(), longitude: z.number().finite().min(-180).max(180).optional(), displayName: optionalTrimmed(160), email: optionalEmail, businessName: optionalTrimmed(160), authorizationNumber: optionalTrimmed(120), materialsAccepted: z.array(z.string().trim().min(1).max(40)).max(20).optional(), pickupAvailable: z.boolean().optional(), serviceRadiusKm: z.number().finite().min(1).max(200).optional() }).superRefine((value, ctx) => {
  if (value.role && !value.areaName) ctx.addIssue({ code: 'custom', path: ['areaName'], message: 'Area is required for registration' });
  if (value.role === 'RECYCLER' && !value.businessName) ctx.addIssue({ code: 'custom', path: ['businessName'], message: 'Business name is required for recycler registration' });
  if (value.role === 'RECYCLER' && !value.materialsAccepted?.length) ctx.addIssue({ code: 'custom', path: ['materialsAccepted'], message: 'At least one accepted material is required for recycler registration' });
});
export const authController = (service: AuthService, emailAuth?: EmailAuthService) => ({
  requestOtp: async (req: Request, res: Response) => { const parsed = phoneSchema.safeParse(req.body?.phone); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'Invalid phone number', 400, { code: 'INVALID_PHONE' }); console.log(JSON.stringify({ event: 'otp_requested', phone: `${parsed.data.slice(0, 2)}******${parsed.data.slice(-2)}` })); return res.json({ success: true, data: { message: await service.requestOtp(parsed.data, req.ip ?? 'unknown') }, message: 'OTP sent successfully' }); },
  verifyOtp: async (req: Request, res: Response) => { const phone = phoneSchema.safeParse(req.body?.phone); const otp = typeof req.body?.otp === 'string' && /^\d{6}$/.test(req.body.otp); const account = phoneAccountInput.safeParse(req.body ?? {}); if (!phone.success || !otp || !account.success) throw new AppError('VALIDATION_ERROR', 'Invalid phone, OTP, or account details', 400, { code: !phone.success ? 'INVALID_PHONE' : !otp ? 'OTP_INVALID' : 'ACCOUNT_DETAILS_INVALID' }); const registration = account.data.role ? account.data as PhoneAccountInput : undefined; const result = await service.verifyOtp(phone.data, req.body.otp, req.ip ?? 'unknown', registration); return res.json({ success: true, data: { token: result.token, refreshToken: 'refreshToken' in result ? result.refreshToken : null, collector: result.collector ?? null, user: result.user ?? null }, message: 'Authentication successful' }); },
  signup: async (req: Request, res: Response) => { if (!emailAuth) throw new AppError('INTERNAL_SERVER_ERROR', 'Email authentication is not configured', 503); const parsed = emailInput.safeParse(req.body); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'Enter a valid email, password, and role', 422, { code: 'INVALID_EMAIL_ACCOUNT' }); const result = await emailAuth.signup(parsed.data, req.ip ?? 'unknown', req.header('user-agent')); return res.status(201).json({ success: true, data: result, message: 'Account created' }); },
  login: async (req: Request, res: Response) => { if (!emailAuth) throw new AppError('INTERNAL_SERVER_ERROR', 'Email authentication is not configured', 503); const parsed = z.object({ email: z.string().trim().email().max(254), password: z.string().min(8).max(128) }).safeParse(req.body); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'Enter a valid email and password', 422, { code: 'INVALID_EMAIL_LOGIN' }); const result = await emailAuth.login(parsed.data.email, parsed.data.password, req.ip ?? 'unknown', req.header('user-agent')); return res.json({ success: true, data: result, message: 'Authentication successful' }); },
  adminLogin: async (req: Request, res: Response) => { if (!emailAuth) throw new AppError('INTERNAL_SERVER_ERROR', 'Email authentication is not configured', 503); const parsed = z.object({ email: z.string().trim().email().max(254), password: z.string().min(8).max(128) }).safeParse(req.body); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'Enter a valid admin email and password', 422, { code: 'INVALID_ADMIN_LOGIN' }); const result = await emailAuth.adminLogin(parsed.data.email, parsed.data.password, req.ip ?? 'unknown', req.header('user-agent')); return res.json({ success: true, data: result, message: 'Admin authentication successful' }); },
  profile: async (req: Request, res: Response) => { if (!emailAuth || !req.identity || !['HOUSEHOLD', 'COLLECTOR', 'RECYCLER'].includes(req.identity.role)) throw new AppError('AUTHENTICATION_REQUIRED', 'A role account is required', 401); const result = await emailAuth.profile(req.identity.collectorId, req.identity.role); return res.json({ success: true, data: result, message: 'Profile retrieved' }); },
  refresh: async (req: Request, res: Response) => { const parsed = z.object({ refreshToken: z.string().min(32).max(500) }).safeParse(req.body); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'A refresh token is required', 422); return res.json({ success:true, data:await service.refresh(parsed.data.refreshToken, req.ip ?? 'unknown'), message:'Session refreshed' }); },
  logout: async (req: Request, res: Response) => { const refreshToken = typeof req.body?.refreshToken === 'string' ? req.body.refreshToken : undefined; await service.logout(refreshToken); return res.json({ success: true, data: { loggedOut: true }, message: 'Logged out successfully' }); }
});
