import type { Request, Response } from 'express'; import { phoneSchema } from '../utils/validation.js'; import { AppError } from '../utils/errors.js'; import type { AuthService, PhoneAccountInput } from '../services/authService.js'; import type { EmailAuthService } from '../services/emailAuthService.js'; import { z } from 'zod';
const emailInput = z.object({ email: z.string().trim().email().max(254), password: z.string().min(8).max(128), role: z.enum(['COLLECTOR', 'RECYCLER']), preferredLanguage: z.enum(['ENGLISH','MARATHI','HINDI','ASSAMESE','BENGALI','BODO','DOGRI','GUJARATI','KANNADA','KASHMIRI','KONKANI','MAITHILI','MALAYALAM','MANIPURI','NEPALI','ODIA','PUNJABI','SANSKRIT','SANTALI','SINDHI','TAMIL','TELUGU','URDU']).default('ENGLISH'), areaName: z.string().trim().max(160).optional(), businessName: z.string().trim().max(160).optional(), authorizationNumber: z.string().trim().max(120).optional(), materialsAccepted: z.array(z.string().max(40)).max(20).optional(), pickupAvailable: z.boolean().optional(), serviceRadiusKm: z.number().finite().min(1).max(200).optional() });
const phoneAccountInput = z.object({ role: z.enum(['COLLECTOR', 'RECYCLER']).optional(), preferredLanguage: z.string().trim().max(40).optional(), areaName: z.string().trim().max(160).optional(), latitude: z.number().finite().min(-90).max(90).optional(), longitude: z.number().finite().min(-180).max(180).optional(), displayName: z.string().trim().max(160).optional(), email: z.string().trim().email().max(254).optional(), businessName: z.string().trim().max(160).optional(), authorizationNumber: z.string().trim().max(120).optional(), materialsAccepted: z.array(z.string().max(40)).max(20).optional(), pickupAvailable: z.boolean().optional(), serviceRadiusKm: z.number().finite().min(1).max(200).optional() });
export const authController = (service: AuthService, emailAuth?: EmailAuthService) => ({
  requestOtp: async (req: Request, res: Response) => { const parsed = phoneSchema.safeParse(req.body?.phone); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'Invalid phone number', 400, { code: 'INVALID_PHONE' }); console.log(JSON.stringify({ event: 'otp_requested', phone: `${parsed.data.slice(0, 2)}******${parsed.data.slice(-2)}` })); return res.json({ success: true, data: { message: await service.requestOtp(parsed.data, req.ip ?? 'unknown') }, message: 'OTP sent successfully' }); },
  verifyOtp: async (req: Request, res: Response) => { const phone = phoneSchema.safeParse(req.body?.phone); const otp = typeof req.body?.otp === 'string' && /^\d{6}$/.test(req.body.otp); const account = phoneAccountInput.safeParse(req.body ?? {}); if (!phone.success || !otp || !account.success) throw new AppError('VALIDATION_ERROR', 'Invalid phone, OTP, or account details', 400, { code: !phone.success ? 'INVALID_PHONE' : 'OTP_INVALID' }); const result = await service.verifyOtp(phone.data, req.body.otp, req.ip ?? 'unknown', account.data as PhoneAccountInput); return res.json({ success: true, data: { token: result.token, collector: result.collector ?? null, user: result.user ?? null }, message: 'Authentication successful' }); },
  signup: async (req: Request, res: Response) => { if (!emailAuth) throw new AppError('INTERNAL_SERVER_ERROR', 'Email authentication is not configured', 503); const parsed = emailInput.safeParse(req.body); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'Enter a valid email, password, and role', 422, { code: 'INVALID_EMAIL_ACCOUNT' }); const result = await emailAuth.signup(parsed.data); return res.status(201).json({ success: true, data: result, message: 'Account created' }); },
  login: async (req: Request, res: Response) => { if (!emailAuth) throw new AppError('INTERNAL_SERVER_ERROR', 'Email authentication is not configured', 503); const parsed = z.object({ email: z.string().trim().email().max(254), password: z.string().min(8).max(128) }).safeParse(req.body); if (!parsed.success) throw new AppError('VALIDATION_ERROR', 'Enter a valid email and password', 422, { code: 'INVALID_EMAIL_LOGIN' }); const result = await emailAuth.login(parsed.data.email, parsed.data.password); return res.json({ success: true, data: result, message: 'Authentication successful' }); },
  profile: async (req: Request, res: Response) => { if (!emailAuth || !req.identity || !['COLLECTOR', 'RECYCLER'].includes(req.identity.role)) throw new AppError('AUTHENTICATION_REQUIRED', 'A role account is required', 401); const result = await emailAuth.profile(req.identity.collectorId, req.identity.role); return res.json({ success: true, data: result, message: 'Profile retrieved' }); },
  logout: async (_req: Request, res: Response) => res.json({ success: true, data: { loggedOut: true }, message: 'Logged out successfully' })
});
