package com.irinteractivestudios.kabadiwalaconnect.ui.supplychain

import java.util.Locale

/**
 * Localized copy for the live supply-chain surface.
 *
 * Most of the app uses Android string resources. This screen also renders
 * server-shaped, interpolated labels, so fixed UI fragments are centralized
 * here to keep those labels localized without translating user/server data.
 */
internal fun localizedSupplyChainText(value: String): String {
    val translations = when (Locale.getDefault().language) {
        "hi" -> HINDI_COPY
        "mr" -> MARATHI_COPY
        else -> emptyMap()
    }
    return translations.entries
        .sortedByDescending { it.key.length }
        .fold(value) { text, (source, target) -> text.replace(source, target) }
}

private val HINDI_COPY = mapOf(
    "Plastic" to "प्लास्टिक", "Cable" to "केबल", "Copper" to "कॉपर", "Pcb" to "PCB",
    "Battery" to "बैटरी", "Motor" to "मोटर", "Magnet" to "चुंबक", "Crt" to "CRT",
    "Lcd panel" to "एलसीडी पैनल", "Other" to "अन्य",
    "Posted" to "पोस्ट किया गया", "Completed" to "पूरा", "Cancelled" to "रद्द",
    "Rejected" to "अस्वीकृत", "Requested" to "माँगी गई", "Accepted" to "स्वीकार",
    "Scheduled" to "निर्धारित", "In transit" to "रास्ते में", "Arrived" to "पहुंच गया",
    "Weighed" to "वजन किया गया", "Pending" to "लंबित", "Disputed" to "विवादित",
    "Ready" to "तैयार", "Forming" to "बन रहा है", "Locked" to "लॉक",
    "Threshold met" to "सीमा पूरी", "Prepared" to "तैयार", "Collector confirmed" to "कलेक्टर ने पुष्टि की",
    "Listed" to "सूचीबद्ध", "Open" to "खुला", "High" to "उच्च", "Review required" to "समीक्षा आवश्यक",
    "Intact" to "सही स्थिति", "Damaged" to "क्षतिग्रस्त", "Partial" to "आंशिक",
    "Ready to sell?" to "बेचने के लिए तैयार हैं?",
    "Share an estimate; your partner confirms weight and price." to "अनुमान साझा करें; आपका पार्टनर पिकअप पर वजन और कीमत की पुष्टि करेगा।",
    "Posting…" to "पोस्ट किया जा रहा है…",
    "Sell scrap" to "स्क्रैप बेचें",
    "My listings" to "मेरी लिस्टिंग",
    "Nearby Kabadiwalas" to "आस-पास के कबाड़ीवाले",
    "Choose a nearby collection partner." to "पास का कलेक्शन पार्टनर चुनें।",
    "No partners nearby" to "आस-पास कोई पार्टनर नहीं",
    "Try another area or refresh later." to "कोई दूसरा क्षेत्र आज़माएँ या बाद में रिफ्रेश करें।",
    "Create a listing to request pickup." to "पिकअप माँगने के लिए लिस्टिंग बनाएँ।",
    "Area not provided" to "क्षेत्र नहीं दिया गया",
    "Approx." to "लगभग",
    "Photo attached · visible to partner" to "फ़ोटो जुड़ी है · पार्टनर को दिखाई देगी",
    "Estimate ·" to "अनुमान ·",
    "Demo range; final value follows inspection." to "डेमो सीमा; जाँच के बाद अंतिम राशि तय होगी।",
    "Choose a partner" to "पार्टनर चुनें",
    "Request pickup ·" to "पिकअप माँगें ·",
    "No active partner in this area yet." to "इस क्षेत्र में अभी कोई सक्रिय पार्टनर नहीं है।",
    "Cancel listing" to "लिस्टिंग रद्द करें",
    "A previous pickup request was cancelled. You can choose another partner." to "पिछली पिकअप माँग रद्द हो गई। आप कोई दूसरा पार्टनर चुन सकते हैं।",
    "Pickup:" to "पिकअप:",
    "Stage:" to "चरण:",
    "Scheduled:" to "निर्धारित:",
    "Final settlement:" to "अंतिम सेटलमेंट:",
    "Choose another time" to "दूसरा समय चुनें",
    "Review settlement" to "सेटलमेंट देखें",
    "Settlement review:" to "सेटलमेंट समीक्षा:",
    "Settlement is under review" to "सेटलमेंट की समीक्षा हो रही है",
    "Cancel this listing?" to "यह लिस्टिंग रद्द करें?",
    "The listing and any pending pickup requests will be cancelled. You can create a new listing later." to "लिस्टिंग और लंबित पिकअप माँगें रद्द हो जाएँगी। आप बाद में नई लिस्टिंग बना सकते हैं।",
    "Keep listing" to "लिस्टिंग रखें",
    "Cancel this pickup?" to "यह पिकअप रद्द करें?",
    "The request will be closed and this listing will be available again if the partner has not started the trip." to "अगर पार्टनर ने यात्रा शुरू नहीं की है, तो माँग बंद होकर यह लिस्टिंग फिर उपलब्ध हो जाएगी।",
    "Keep pickup" to "पिकअप रखें",
    "Sell your scrap" to "अपना स्क्रैप बेचें",
    "A nearby Kabadiwala weighs it and confirms payment." to "पास का कबाड़ीवाला इसका वजन करके भुगतान की पुष्टि करता है।",
    "Ready to sell?" to "बेचने के लिए तैयार हैं?",
    "Add material details. Your partner confirms weight and price at pickup." to "सामान का विवरण जोड़ें। आपका पार्टनर पिकअप के समय वजन और कीमत की पुष्टि करेगा।",
    "Material" to "सामान",
    "Handle with care" to "सावधानी से संभालें",
    "Do not dismantle, burn, puncture or mix it. Keep it away from children, heat and water." to "इसे खोलें, जलाएँ, छेद न करें और दूसरे सामान में न मिलाएँ। बच्चों, गर्मी और पानी से दूर रखें।",
    "I understand the warning" to "मैं चेतावनी समझता/समझती हूँ",
    "Condition" to "स्थिति",
    "Approximate weight · kg" to "अनुमानित वजन · किलो",
    "Enter a weight between 0 and 500 kg" to "0 से 500 किलो के बीच वजन दर्ज करें",
    "Pickup area" to "पिकअप क्षेत्र",
    "Add a little more detail, for example an area or landmark" to "थोड़ा और विवरण दें, जैसे क्षेत्र या लैंडमार्क",
    "Data-bearing device" to "डेटा वाला उपकरण",
    "For phones, laptops, drives or other personal-data devices." to "फ़ोन, लैपटॉप, ड्राइव या निजी डेटा वाले अन्य उपकरणों के लिए।",
    "May contain personal data" to "इसमें निजी डेटा हो सकता है",
    "I removed my account" to "मैंने अपना अकाउंट हटा दिया है",
    "Request destruction evidence" to "नष्ट करने का प्रमाण माँगें",
    "Attach scrap photo" to "स्क्रैप फ़ोटो जोड़ें",
    "Photo attached" to "फ़ोटो जुड़ी है",
    "Remove" to "हटाएँ",
    "Price range" to "कीमत सीमा",
    "Reference only; final offer follows inspection." to "केवल संदर्भ; जाँच के बाद अंतिम ऑफ़र तय होगा।",
    "Notes (optional)" to "नोट्स (वैकल्पिक)",
    "Post listing" to "लिस्टिंग पोस्ट करें",
    "Photo attached locally" to "फ़ोटो स्थानीय रूप से जुड़ी है",
    "Prototype demo data" to "प्रोटोटाइप डेमो डेटा",
    "Prototype data is labelled. Final weight, grade and payment are confirmed at handover." to "प्रोटोटाइप डेटा को चिह्नित किया गया है। अंतिम वजन, ग्रेड और भुगतान हैंडओवर पर तय होते हैं।",
    "Collection desk" to "कलेक्शन डेस्क",
    "Scrap inventory" to "स्क्रैप इन्वेंटरी",
    "Household pickups" to "हाउसहोल्ड पिकअप",
    "Recycler sales" to "रीसाइक्लर बिक्री",
    "Households → inventory → verified recyclers" to "हाउसहोल्ड → इन्वेंटरी → सत्यापित रीसाइक्लर",
    "Record lot" to "लॉट दर्ज करें",
    "requests" to "माँगें",
    "scheduled" to "निर्धारित",
    "Pickup queue" to "पिकअप कतार",
    "No household pickups" to "कोई हाउसहोल्ड पिकअप नहीं",
    "New requests will appear here." to "नई माँगें यहाँ दिखाई देंगी।",
    "Inventory is empty" to "इन्वेंटरी खाली है",
    "Complete a pickup to add weighed material." to "तौला हुआ सामान जोड़ने के लिए पिकअप पूरा करें।",
    "Create recycler lot" to "रीसाइक्लर लॉट बनाएँ",
    "Bulk lots" to "बल्क लॉट",
    "No bulk lots yet" to "अभी कोई बल्क लॉट नहीं",
    "Reserve available inventory when ready." to "तैयार होने पर उपलब्ध इन्वेंटरी आरक्षित करें।",
    "Recycler offers" to "रीसाइक्लर ऑफ़र",
    "No offers yet" to "अभी कोई ऑफ़र नहीं",
    "Offers on listed lots appear here." to "लिस्ट किए गए लॉट के ऑफ़र यहाँ दिखाई देंगे।",
    "Captured lot records" to "दर्ज किए गए लॉट के रिकॉर्ड",
    "Saved records stay visible. Use weighed inventory to publish a recycler lot." to "सहेजे गए रिकॉर्ड दिखाई देते रहेंगे। रीसाइक्लर लॉट प्रकाशित करने के लिए तौली हुई इन्वेंटरी इस्तेमाल करें।",
    "Accept pickup" to "पिकअप स्वीकार करें",
    "Decline" to "मना करें",
    "Confirm ready" to "तैयारी की पुष्टि करें",
    "Schedule" to "समय तय करें",
    "Start now" to "अभी शुरू करें",
    "Start trip" to "यात्रा शुरू करें",
    "Mark arrived" to "पहुंचना दर्ज करें",
    "Record weight" to "वजन दर्ज करें",
    "Added to inventory ·" to "इन्वेंटरी में जोड़ा गया ·",
    "Report issue / reassign" to "समस्या बताएँ / फिर से सौंपें",
    "Schedule collection" to "कलेक्शन का समय तय करें",
    "Choose a time for this pickup." to "इस पिकअप के लिए समय चुनें।",
    "Confirm time" to "समय की पुष्टि करें",
    "Reason (optional)" to "कारण (वैकल्पिक)",
    "Return for reassignment" to "फिर से सौंपने के लिए लौटाएँ",
    "Why reassign?" to "फिर से क्यों सौंपें?",
    "No-show" to "कोई नहीं आया",
    "Reassign" to "फिर से सौंपें",
    "Not now" to "अभी नहीं",
    "Check weight and value before accepting." to "स्वीकार करने से पहले वजन और राशि जाँचें।",
    "Raise an issue instead" to "इसके बजाय समस्या बताएँ",
    "Reason" to "कारण",
    "What should be reviewed?" to "क्या जाँचा जाना चाहिए?",
    "Submit issue" to "समस्या भेजें",
    "Final weighing" to "अंतिम वजन",
    "The household sees this amount immediately." to "हाउसहोल्ड यह राशि तुरंत देखेगा।",
    "Actual weight · kg" to "वास्तविक वजन · किलो",
    "Rate · ₹/kg" to "रेट · ₹/किलो",
    "Final material" to "अंतिम सामान",
    "Grade" to "ग्रेड",
    "Settlement preview ·" to "सेटलमेंट का अनुमान ·",
    "Complete pickup" to "पिकअप पूरा करें",
    "free" to "उपलब्ध",
    "Grade:" to "ग्रेड:",
    "Reserved" to "आरक्षित",
    "sold" to "बिका",
    "cost" to "लागत",
    "Saved on server" to "सर्वर पर सहेजा गया",
    "Waiting to sync" to "सिंक की प्रतीक्षा",
    "captured record, not a recycler lot." to "दर्ज रिकॉर्ड, रीसाइक्लर लॉट नहीं।",
    "Reserved inventory ·" to "आरक्षित इन्वेंटरी ·",
    "Cancel lot and release stock" to "लॉट रद्द करें और स्टॉक छोड़ें",
    "Recycler offer" to "रीसाइक्लर ऑफ़र",
    "Accept" to "स्वीकार करें",
    "Counter" to "जवाबी ऑफ़र",
    "Reject offer" to "ऑफ़र अस्वीकार करें",
    "Reject recycler offer" to "रीसाइक्लर ऑफ़र अस्वीकार करें",
    "Counter-offer" to "जवाबी ऑफ़र",
    "Note (optional)" to "नोट (वैकल्पिक)",
    "Send counter" to "जवाबी ऑफ़र भेजें",
    "Create recycler bulk lot" to "रीसाइक्लर बल्क लॉट बनाएँ",
    "Only available inventory can be reserved. This lot is for verified recyclers." to "केवल उपलब्ध इन्वेंटरी आरक्षित की जा सकती है। यह लॉट सत्यापित रीसाइक्लर के लिए है।",
    "available" to "उपलब्ध",
    "Asking rate · ₹/kg" to "माँगा गया रेट · ₹/किलो",
    "Minimum acceptable rate · ₹/kg (optional)" to "न्यूनतम स्वीकार्य रेट · ₹/किलो (वैकल्पिक)",
    "Notes for recyclers (optional)" to "रीसाइक्लर के लिए नोट्स (वैकल्पिक)",
    "List for recyclers" to "रीसाइक्लर के लिए लिस्ट करें",
    "Buy recyclable material" to "रीसाइक्लिंग योग्य सामान खरीदें",
    "Browse bulk lots or publish facility demand." to "बल्क लॉट देखें या सुविधा की माँग प्रकाशित करें।",
    "Publish demand" to "माँग प्रकाशित करें",
    "Available collector lots" to "उपलब्ध कलेक्टर लॉट",
    "No lots available" to "कोई लॉट उपलब्ध नहीं",
    "Matching lots will appear here." to "मेल खाते लॉट यहाँ दिखाई देंगे।",
    "My offers" to "मेरे ऑफ़र",
    "Make an offer on a listed lot." to "लिस्ट किए गए लॉट पर ऑफ़र दें।",
    "Your offer" to "आपका ऑफ़र",
    "Withdraw offer" to "ऑफ़र वापस लें",
    "My demand" to "मेरी माँग",
    "Pools" to "पूल",
    "No pools yet" to "अभी कोई पूल नहीं",
    "Collectors can combine reserved stock for your demand." to "कलेक्टर आपकी माँग के लिए आरक्षित स्टॉक मिला सकते हैं।",
    "Awaiting receipts" to "रसीद की प्रतीक्षा",
    "No handovers yet" to "अभी कोई हैंडओवर नहीं",
    "Confirmed QR handovers will appear here." to "पुष्टि किए गए QR हैंडओवर यहाँ दिखाई देंगे।",
    "collector lot" to "कलेक्टर लॉट",
    "Make offer" to "ऑफ़र दें",
    "Your offer:" to "आपका ऑफ़र:",
    "Accepted · waiting for QR handover." to "स्वीकार किया गया · QR हैंडओवर की प्रतीक्षा।",
    "Offer on" to "ऑफ़र —",
    "Send offer" to "ऑफ़र भेजें",
    "Publish procurement demand" to "खरीद की माँग प्रकाशित करें",
    "Needed quantity · kg" to "ज़रूरी मात्रा · किलो",
    "Minimum lot · kg" to "न्यूनतम लॉट · किलो",
    "Procurement radius · km" to "खरीद का दायरा · किमी",
    "Maximum rate · ₹/kg (optional)" to "अधिकतम रेट · ₹/किलो (वैकल्पिक)",
    "Publish demand" to "माँग प्रकाशित करें",
    "Need" to "ज़रूरत",
    "Within" to "दायरे में",
    "Update demand" to "माँग अपडेट करें",
    "Update procurement demand" to "खरीद की माँग अपडेट करें",
    "Required quantity · kg" to "ज़रूरी मात्रा · किलो",
    "Radius · km" to "दायरा · किमी",
    "Maximum rate · ₹/kg" to "अधिकतम रेट · ₹/किलो",
    "Save demand" to "माँग सहेजें",
    "Formal route desk" to "औपचारिक रूट डेस्क",
    "Compare routes, pools and passport evidence." to "रूट, पूल और पासपोर्ट प्रमाण की तुलना करें।",
    "Platform evidence—not a government certificate or guaranteed price." to "प्लेटफ़ॉर्म प्रमाण—सरकारी प्रमाणपत्र या गारंटीकृत कीमत नहीं।",
    "Formal Route Advantage" to "औपचारिक रूट का लाभ",
    "Compare rate, pickup readiness and logistics cost." to "रेट, पिकअप तैयारी और लॉजिस्टिक्स लागत की तुलना करें।",
    "Compare verified routes" to "सत्यापित रूट की तुलना करें",
    "Reference baseline:" to "संदर्भ आधार:",
    "Safety-aware routing" to "सुरक्षा-सचेत रूटिंग",
    "Check handling before moving hazardous or data-bearing material." to "खतरनाक या डेटा वाले सामान को ले जाने से पहले हैंडलिंग जाँचें।",
    "Check handling route" to "हैंडलिंग रूट जाँचें",
    "Cooperative pooling" to "सहकारी पूलिंग",
    "Reserve available stock; thresholds and contributions stay visible." to "उपलब्ध स्टॉक आरक्षित करें; सीमा और योगदान दिखाई देते रहेंगे।",
    "Open pool" to "पूल खोलें",
    "Join with reserved stock" to "आरक्षित स्टॉक के साथ जुड़ें",
    "Demand-triggered suggestions" to "माँग पर आधारित सुझाव",
    "No open demand. New pools appear after a Recycler publishes demand." to "कोई खुली माँग नहीं। रीसाइक्लर के माँग प्रकाशित करने के बाद नए पूल दिखाई देंगे।",
    "Demand intelligence" to "माँग की जानकारी",
    "Platform signal, not a guaranteed sale." to "प्लेटफ़ॉर्म संकेत, पक्की बिक्री नहीं।",
    "Collector Growth Passport" to "कलेक्टर ग्रोथ पासपोर्ट",
    "Safety gate" to "सुरक्षा गेट",
    "Acknowledge" to "स्वीकार करें",
    "Showing saved evidence. Changes wait for the server." to "सहेजा गया प्रमाण दिखाया जा रहा है। बदलाव सर्वर की प्रतीक्षा में हैं।",
    "Kabadiwala Connect advantage" to "कबाड़ीवाला कनेक्ट का लाभ",
    "9 features" to "९ सुविधाएँ",
    "One field workflow from doorstep pickup to fair, traceable recycler settlement." to "दरवाज़े से पिकअप से लेकर उचित और ट्रेस करने योग्य रीसाइक्लर सेटलमेंट तक एक फील्ड वर्कफ़्लो।",
    "Direct pickup from your door" to "आपके दरवाज़े से सीधा पिकअप",
    "Collector-focused ways of working" to "कलेक्टर-केंद्रित काम करने के तरीके",
    "Optimized route benefits" to "ऑप्टिमाइज़्ड रूट के लाभ",
    "Factory demand for material data" to "मटेरियल डेटा की फैक्ट्री माँग",
    "Coordinated shared pooling" to "समन्वित साझा पूलिंग",
    "Paper trail without internet" to "इंटरनेट के बिना कागज़ी रिकॉर्ड",
    "Payment fairness & rules" to "भुगतान की निष्पक्षता और नियम",
    "Collector growth tracking" to "कलेक्टर प्रगति ट्रैकिंग",
    "Key language availability" to "प्रमुख भाषाओं की उपलब्धता",
    "LIVE" to "लाइव",
    "PILOT" to "पायलट",
    "LIVE = connected workflow is available. PILOT = the workflow is built, but estimates or connectivity still matter." to "लाइव = कनेक्टेड वर्कफ़्लो उपलब्ध है। पायलट = वर्कफ़्लो तैयार है, लेकिन अनुमान या कनेक्टिविटी अभी ज़रूरी है।",
    "Pool ·" to "पूल ·",
    "contributors" to "योगदानकर्ता",
    "Lock pool" to "पूल लॉक करें",
    "Prepare QR" to "QR तैयार करें",
    "Leave" to "छोड़ें",
    "Reserved until the pooled handover is settled." to "पूल हैंडओवर का सेटलमेंट होने तक आरक्षित।",
    "Quantity · kg" to "मात्रा · किलो",
    "Expected rate · ₹/kg" to "अपेक्षित रेट · ₹/किलो",
    "Reserve stock" to "स्टॉक आरक्षित करें",
    "Material passport handover" to "मटेरियल पासपोर्ट हैंडओवर",
    "Quoted value" to "कोट की राशि",
    "Confirm collector side" to "कलेक्टर पक्ष की पुष्टि करें",
    "Show this one-time QR to the verified Recycler for scan and receipt." to "स्कैन और रसीद के लिए यह एक बार वाला QR सत्यापित रीसाइक्लर को दिखाएँ।",
    "Passport" to "पासपोर्ट",
    "Risk flags" to "जोखिम संकेत",
    "Receipt completed. The one-time QR is no longer active; inspect the passport timeline for evidence." to "रसीद पूरी हुई। एक बार वाला QR अब सक्रिय नहीं है; प्रमाण के लिए पासपोर्ट टाइमलाइन देखें।",
    "Review formal settlement" to "औपचारिक सेटलमेंट देखें",
    "Accept settlement" to "सेटलमेंट स्वीकार करें",
    "Try detection again" to "जाँच फिर से करें",
    "Loading scrap photos…" to "स्क्रैप फ़ोटो लोड हो रही हैं…",
    "Some photos could not be processed. Please choose a JPEG, PNG, or WebP image." to "कुछ फ़ोटो प्रोसेस नहीं हो सकीं। JPEG, PNG या WebP इमेज चुनें।",
    "angles available" to "एंगल उपलब्ध",
    "angle available" to "एंगल उपलब्ध",
    "Retry" to "फिर कोशिश करें",
    "Refresh" to "रिफ्रेश करें",
    "Pending inspection" to "जाँच लंबित",
    " kg" to " किलो"
)

private val MARATHI_COPY = mapOf(
    "Plastic" to "प्लास्टिक", "Cable" to "केबल", "Copper" to "कॉपर", "Pcb" to "PCB",
    "Battery" to "बॅटरी", "Motor" to "मोटर", "Magnet" to "चुंबक", "Crt" to "CRT",
    "Lcd panel" to "एलसीडी पॅनेल", "Other" to "इतर",
    "Posted" to "पोस्ट केले", "Completed" to "पूर्ण", "Cancelled" to "रद्द",
    "Rejected" to "नाकारले", "Requested" to "विनंती केले", "Accepted" to "स्वीकारले",
    "Scheduled" to "नियोजित", "In transit" to "प्रवासात", "Arrived" to "पोहोचले",
    "Weighed" to "वजन केले", "Pending" to "प्रलंबित", "Disputed" to "वादग्रस्त",
    "Ready" to "तयार", "Forming" to "तयार होत आहे", "Locked" to "लॉक",
    "Threshold met" to "मर्यादा पूर्ण", "Prepared" to "तयार", "Collector confirmed" to "कलेक्टरने पुष्टी केली",
    "Listed" to "लिस्ट केले", "Open" to "उघडे", "High" to "उच्च", "Review required" to "पुनरावलोकन आवश्यक",
    "Intact" to "चांगल्या स्थितीत", "Damaged" to "नुकसान झालेले", "Partial" to "अंशतः",
    "Ready to sell?" to "विक्रीसाठी तयार आहात?",
    "Share an estimate; your partner confirms weight and price." to "अंदाज शेअर करा; तुमचा पार्टनर पिकअपवेळी वजन आणि किंमतीची पुष्टी करेल.",
    "Posting…" to "पोस्ट करत आहे…",
    "Sell scrap" to "स्क्रॅप विका",
    "My listings" to "माझ्या लिस्टिंग",
    "Nearby Kabadiwalas" to "जवळचे कबाडीवाले",
    "Choose a nearby collection partner." to "जवळचा कलेक्शन पार्टनर निवडा.",
    "No partners nearby" to "जवळपास पार्टनर नाही",
    "Try another area or refresh later." to "दुसरे क्षेत्र वापरा किंवा नंतर रिफ्रेश करा.",
    "Create a listing to request pickup." to "पिकअप मागण्यासाठी लिस्टिंग तयार करा.",
    "Area not provided" to "क्षेत्र दिलेले नाही",
    "Approx." to "अंदाजे",
    "Photo attached · visible to partner" to "फोटो जोडला · पार्टनरला दिसेल",
    "Estimate ·" to "अंदाज ·",
    "Demo range; final value follows inspection." to "डेमो श्रेणी; तपासणीनंतर अंतिम रक्कम ठरेल.",
    "Choose a partner" to "पार्टनर निवडा",
    "Request pickup ·" to "पिकअप मागा ·",
    "No active partner in this area yet." to "या क्षेत्रात अजून सक्रिय पार्टनर नाही.",
    "Cancel listing" to "लिस्टिंग रद्द करा",
    "A previous pickup request was cancelled. You can choose another partner." to "मागील पिकअप विनंती रद्द झाली. तुम्ही दुसरा पार्टनर निवडू शकता.",
    "Pickup:" to "पिकअप:",
    "Stage:" to "टप्पा:",
    "Scheduled:" to "नियोजित:",
    "Final settlement:" to "अंतिम सेटलमेंट:",
    "Choose another time" to "दुसरी वेळ निवडा",
    "Review settlement" to "सेटलमेंट तपासा",
    "Settlement review:" to "सेटलमेंट पुनरावलोकन:",
    "Settlement is under review" to "सेटलमेंटचे पुनरावलोकन सुरू आहे",
    "Cancel this listing?" to "हे लिस्टिंग रद्द करायचे?",
    "The listing and any pending pickup requests will be cancelled. You can create a new listing later." to "लिस्टिंग आणि प्रलंबित पिकअप विनंत्या रद्द होतील. तुम्ही नंतर नवीन लिस्टिंग तयार करू शकता.",
    "Keep listing" to "लिस्टिंग ठेवा",
    "Cancel this pickup?" to "हा पिकअप रद्द करायचा?",
    "The request will be closed and this listing will be available again if the partner has not started the trip." to "पार्टनरने प्रवास सुरू केला नसेल तर विनंती बंद होईल आणि हे लिस्टिंग पुन्हा उपलब्ध होईल.",
    "Keep pickup" to "पिकअप ठेवा",
    "Sell your scrap" to "तुमचा स्क्रॅप विका",
    "A nearby Kabadiwala weighs it and confirms payment." to "जवळचा कबाडीवाला वजन करून पेमेंटची पुष्टी करतो.",
    "Add material details. Your partner confirms weight and price at pickup." to "वस्तूंचे तपशील जोडा. तुमचा पार्टनर पिकअपवेळी वजन आणि किंमतीची पुष्टी करतो.",
    "Material" to "वस्तू",
    "Handle with care" to "काळजीपूर्वक हाताळा",
    "Do not dismantle, burn, puncture or mix it. Keep it away from children, heat and water." to "ते उघडू, जाळू, छिद्र करू किंवा इतर वस्तूंमध्ये मिसळू नका. मुलांपासून, उष्णता आणि पाण्यापासून दूर ठेवा.",
    "I understand the warning" to "मला ही सूचना समजली आहे",
    "Condition" to "स्थिती",
    "Approximate weight · kg" to "अंदाजे वजन · किलो",
    "Enter a weight between 0 and 500 kg" to "0 ते 500 किलोमधील वजन भरा",
    "Pickup area" to "पिकअप क्षेत्र",
    "Add a little more detail, for example an area or landmark" to "थोडे अधिक तपशील द्या, उदाहरणार्थ क्षेत्र किंवा लँडमार्क",
    "Data-bearing device" to "डेटा असलेले उपकरण",
    "For phones, laptops, drives or other personal-data devices." to "फोन, लॅपटॉप, ड्राइव्ह किंवा वैयक्तिक डेटा असलेल्या इतर उपकरणांसाठी.",
    "May contain personal data" to "यात वैयक्तिक डेटा असू शकतो",
    "I removed my account" to "मी माझे खाते काढले आहे",
    "Request destruction evidence" to "नष्ट केल्याचा पुरावा मागा",
    "Attach scrap photo" to "स्क्रॅपचा फोटो जोडा",
    "Photo attached" to "फोटो जोडला",
    "Remove" to "काढा",
    "Price range" to "किंमत श्रेणी",
    "Reference only; final offer follows inspection." to "फक्त संदर्भ; तपासणीनंतर अंतिम ऑफर ठरेल.",
    "Notes (optional)" to "नोंदी (पर्यायी)",
    "Post listing" to "लिस्टिंग पोस्ट करा",
    "Photo attached locally" to "फोटो स्थानिकरित्या जोडला",
    "Prototype demo data" to "प्रोटोटाइप डेमो डेटा",
    "Prototype data is labelled. Final weight, grade and payment are confirmed at handover." to "प्रोटोटाइप डेटा चिन्हांकित आहे. अंतिम वजन, ग्रेड आणि पेमेंट हँडओव्हरवेळी निश्चित होतात.",
    "Collection desk" to "कलेक्शन डेस्क",
    "Scrap inventory" to "स्क्रॅप साठा",
    "Household pickups" to "घरगुती पिकअप",
    "Recycler sales" to "रीसायकलर विक्री",
    "Households → inventory → verified recyclers" to "घरगुती → साठा → सत्यापित रीसायकलर",
    "Record lot" to "लॉट नोंदवा",
    "requests" to "विनंत्या",
    "scheduled" to "नियोजित",
    "Pickup queue" to "पिकअप रांग",
    "No household pickups" to "घरगुती पिकअप नाहीत",
    "New requests will appear here." to "नवीन विनंत्या येथे दिसतील.",
    "Inventory is empty" to "साठा रिकामा आहे",
    "Complete a pickup to add weighed material." to "वजन केलेली वस्तू जोडण्यासाठी पिकअप पूर्ण करा.",
    "Create recycler lot" to "रीसायकलर लॉट तयार करा",
    "Bulk lots" to "बल्क लॉट",
    "No bulk lots yet" to "अजून बल्क लॉट नाहीत",
    "Reserve available inventory when ready." to "तयार झाल्यावर उपलब्ध साठा राखीव ठेवा.",
    "Recycler offers" to "रीसायकलर ऑफर",
    "No offers yet" to "अजून ऑफर नाहीत",
    "Offers on listed lots appear here." to "लिस्ट केलेल्या लॉटच्या ऑफर येथे दिसतील.",
    "Captured lot records" to "नोंदवलेल्या लॉटचे रेकॉर्ड",
    "Saved records stay visible. Use weighed inventory to publish a recycler lot." to "जतन केलेले रेकॉर्ड दिसत राहतील. रीसायकलर लॉट प्रकाशित करण्यासाठी वजन केलेला साठा वापरा.",
    "Accept pickup" to "पिकअप स्वीकारा",
    "Decline" to "नकार द्या",
    "Confirm ready" to "तयारीची पुष्टी करा",
    "Schedule" to "वेळ ठरवा",
    "Start now" to "आता सुरू करा",
    "Start trip" to "प्रवास सुरू करा",
    "Mark arrived" to "आगमन नोंदवा",
    "Record weight" to "वजन नोंदवा",
    "Added to inventory ·" to "साठ्यात जोडले ·",
    "Report issue / reassign" to "समस्या कळवा / पुन्हा सोपवा",
    "Schedule collection" to "कलेक्शनचे वेळापत्रक ठरवा",
    "Choose a time for this pickup." to "या पिकअपसाठी वेळ निवडा.",
    "Confirm time" to "वेळेची पुष्टी करा",
    "Reason (optional)" to "कारण (पर्यायी)",
    "Return for reassignment" to "पुन्हा सोपवण्यासाठी परत करा",
    "Why reassign?" to "पुन्हा का सोपवायचे?",
    "No-show" to "कोणी आले नाही",
    "Reassign" to "पुन्हा सोपवा",
    "Not now" to "आत्ता नाही",
    "Check weight and value before accepting." to "स्वीकारण्यापूर्वी वजन आणि रक्कम तपासा.",
    "Raise an issue instead" to "त्याऐवजी समस्या कळवा",
    "Reason" to "कारण",
    "What should be reviewed?" to "कशाचे पुनरावलोकन करायचे?",
    "Submit issue" to "समस्या पाठवा",
    "Final weighing" to "अंतिम वजन",
    "The household sees this amount immediately." to "घरगुती वापरकर्त्याला ही रक्कम लगेच दिसते.",
    "Actual weight · kg" to "प्रत्यक्ष वजन · किलो",
    "Rate · ₹/kg" to "दर · ₹/किलो",
    "Final material" to "अंतिम वस्तू",
    "Grade" to "ग्रेड",
    "Settlement preview ·" to "सेटलमेंट अंदाज ·",
    "Complete pickup" to "पिकअप पूर्ण करा",
    "free" to "मोकळे",
    "Grade:" to "ग्रेड:",
    "Reserved" to "राखीव",
    "sold" to "विकले",
    "cost" to "खर्च",
    "Saved on server" to "सर्व्हरवर जतन केले",
    "Waiting to sync" to "सिंकची प्रतीक्षा",
    "captured record, not a recycler lot." to "नोंदवलेले रेकॉर्ड, रीसायकलर लॉट नाही.",
    "Reserved inventory ·" to "राखीव साठा ·",
    "Cancel lot and release stock" to "लॉट रद्द करून स्टॉक मोकळा करा",
    "Recycler offer" to "रीसायकलर ऑफर",
    "Accept" to "स्वीकारा",
    "Counter" to "प्रतिऑफर",
    "Reject offer" to "ऑफर नाकारा",
    "Reject recycler offer" to "रीसायकलर ऑफर नाकारा",
    "Counter-offer" to "प्रतिऑफर",
    "Note (optional)" to "नोंद (पर्यायी)",
    "Send counter" to "प्रतिऑफर पाठवा",
    "Create recycler bulk lot" to "रीसायकलर बल्क लॉट तयार करा",
    "Only available inventory can be reserved. This lot is for verified recyclers." to "फक्त उपलब्ध साठा राखीव ठेवता येतो. हा लॉट सत्यापित रीसायकलरसाठी आहे.",
    "available" to "उपलब्ध",
    "Asking rate · ₹/kg" to "मागितलेला दर · ₹/किलो",
    "Minimum acceptable rate · ₹/kg (optional)" to "किमान स्वीकार्य दर · ₹/किलो (पर्यायी)",
    "Notes for recyclers (optional)" to "रीसायकलरसाठी नोंदी (पर्यायी)",
    "List for recyclers" to "रीसायकलरसाठी लिस्ट करा",
    "Buy recyclable material" to "रीसायकल करता येणारी वस्तू खरेदी करा",
    "Browse bulk lots or publish facility demand." to "बल्क लॉट पाहा किंवा सुविधेची मागणी प्रकाशित करा.",
    "Publish demand" to "मागणी प्रकाशित करा",
    "Available collector lots" to "उपलब्ध कलेक्टर लॉट",
    "No lots available" to "लॉट उपलब्ध नाहीत",
    "Matching lots will appear here." to "जुळणारे लॉट येथे दिसतील.",
    "My offers" to "माझ्या ऑफर",
    "Make an offer on a listed lot." to "लिस्ट केलेल्या लॉटवर ऑफर द्या.",
    "Your offer" to "तुमची ऑफर",
    "Withdraw offer" to "ऑफर मागे घ्या",
    "My demand" to "माझी मागणी",
    "Pools" to "पूल",
    "No pools yet" to "अजून पूल नाहीत",
    "Collectors can combine reserved stock for your demand." to "तुमच्या मागणीसाठी कलेक्टर राखीव स्टॉक एकत्र करू शकतात.",
    "Awaiting receipts" to "पावतीची प्रतीक्षा",
    "No handovers yet" to "अजून हँडओव्हर नाहीत",
    "Confirmed QR handovers will appear here." to "पुष्टी केलेले QR हँडओव्हर येथे दिसतील.",
    "collector lot" to "कलेक्टर लॉट",
    "Make offer" to "ऑफर द्या",
    "Your offer:" to "तुमची ऑफर:",
    "Accepted · waiting for QR handover." to "स्वीकारले · QR हँडओव्हरची प्रतीक्षा.",
    "Offer on" to "ऑफर —",
    "Send offer" to "ऑफर पाठवा",
    "Publish procurement demand" to "खरेदीची मागणी प्रकाशित करा",
    "Needed quantity · kg" to "आवश्यक प्रमाण · किलो",
    "Minimum lot · kg" to "किमान लॉट · किलो",
    "Procurement radius · km" to "खरेदीचा परिसर · किमी",
    "Maximum rate · ₹/kg (optional)" to "कमाल दर · ₹/किलो (पर्यायी)",
    "Need" to "गरज",
    "Within" to "च्या आत",
    "Update demand" to "मागणी अपडेट करा",
    "Update procurement demand" to "खरेदीची मागणी अपडेट करा",
    "Required quantity · kg" to "आवश्यक प्रमाण · किलो",
    "Radius · km" to "परिसर · किमी",
    "Maximum rate · ₹/kg" to "कमाल दर · ₹/किलो",
    "Save demand" to "मागणी जतन करा",
    "Formal route desk" to "औपचारिक रूट डेस्क",
    "Compare routes, pools and passport evidence." to "रूट, पूल आणि पासपोर्ट पुराव्यांची तुलना करा.",
    "Platform evidence—not a government certificate or guaranteed price." to "प्लॅटफॉर्म पुरावा—सरकारी प्रमाणपत्र किंवा हमीची किंमत नाही.",
    "Formal Route Advantage" to "औपचारिक रूटचा फायदा",
    "Compare rate, pickup readiness and logistics cost." to "दर, पिकअपची तयारी आणि लॉजिस्टिक्स खर्चाची तुलना करा.",
    "Compare verified routes" to "सत्यापित रूटची तुलना करा",
    "Reference baseline:" to "संदर्भ आधार:",
    "Safety-aware routing" to "सुरक्षित रूटिंग",
    "Check handling before moving hazardous or data-bearing material." to "धोकादायक किंवा डेटा असलेली वस्तू हलवण्यापूर्वी हाताळणी तपासा.",
    "Check handling route" to "हाताळणी रूट तपासा",
    "Cooperative pooling" to "सहकारी पूलिंग",
    "Reserve available stock; thresholds and contributions stay visible." to "उपलब्ध स्टॉक राखीव ठेवा; मर्यादा आणि योगदान दिसत राहतील.",
    "Open pool" to "पूल उघडा",
    "Join with reserved stock" to "राखीव स्टॉकसह सामील व्हा",
    "Demand-triggered suggestions" to "मागणीवर आधारित सूचना",
    "No open demand. New pools appear after a Recycler publishes demand." to "खुली मागणी नाही. रीसायकलरने मागणी प्रकाशित केल्यानंतर नवीन पूल दिसतील.",
    "Demand intelligence" to "मागणीची माहिती",
    "Platform signal, not a guaranteed sale." to "प्लॅटफॉर्म संकेत, हमीची विक्री नाही.",
    "Collector Growth Passport" to "कलेक्टर ग्रोथ पासपोर्ट",
    "Safety gate" to "सुरक्षा गेट",
    "Acknowledge" to "मान्य करा",
    "Showing saved evidence. Changes wait for the server." to "जतन केलेला पुरावा दाखवत आहे. बदल सर्व्हरच्या प्रतीक्षेत आहेत.",
    "Kabadiwala Connect advantage" to "कबाडीवाला कनेक्टचा फायदा",
    "9 features" to "९ वैशिष्ट्ये",
    "One field workflow from doorstep pickup to fair, traceable recycler settlement." to "दारापासून पिकअप ते न्याय्य आणि ट्रेस करण्यायोग्य रीसायकलर सेटलमेंटपर्यंत एक फील्ड वर्कफ्लो.",
    "Direct pickup from your door" to "तुमच्या दारापासून थेट पिकअप",
    "Collector-focused ways of working" to "कलेक्टर-केंद्रित कामाची पद्धत",
    "Optimized route benefits" to "ऑप्टिमाइझ्ड रूटचे फायदे",
    "Factory demand for material data" to "मटेरियल डेटासाठी कारखान्याची मागणी",
    "Coordinated shared pooling" to "समन्वयित शेअर्ड पूलिंग",
    "Paper trail without internet" to "इंटरनेटशिवाय कागदी पुरावा",
    "Payment fairness & rules" to "पेमेंटमधील न्याय आणि नियम",
    "Collector growth tracking" to "कलेक्टर प्रगती ट्रॅकिंग",
    "Key language availability" to "प्रमुख भाषांची उपलब्धता",
    "LIVE" to "लाईव्ह",
    "PILOT" to "पायलट",
    "LIVE = connected workflow is available. PILOT = the workflow is built, but estimates or connectivity still matter." to "लाईव्ह = कनेक्टेड वर्कफ्लो उपलब्ध आहे. पायलट = वर्कफ्लो तयार आहे, पण अंदाज किंवा कनेक्टिव्हिटी महत्त्वाची आहे.",
    "Pool ·" to "पूल ·",
    "contributors" to "योगदानकर्ते",
    "Lock pool" to "पूल लॉक करा",
    "Prepare QR" to "QR तयार करा",
    "Leave" to "बाहेर पडा",
    "Reserved until the pooled handover is settled." to "पूल हँडओव्हरचे सेटलमेंट होईपर्यंत राखीव.",
    "Quantity · kg" to "प्रमाण · किलो",
    "Expected rate · ₹/kg" to "अपेक्षित दर · ₹/किलो",
    "Reserve stock" to "स्टॉक राखीव ठेवा",
    "Material passport handover" to "मटेरियल पासपोर्ट हँडओव्हर",
    "Quoted value" to "कोट केलेली रक्कम",
    "Confirm collector side" to "कलेक्टर बाजूची पुष्टी करा",
    "Show this one-time QR to the verified Recycler for scan and receipt." to "स्कॅन आणि पावतीसाठी हा एकदाच वापरता येणारा QR सत्यापित रीसायकलरला दाखवा.",
    "Passport" to "पासपोर्ट",
    "Risk flags" to "जोखीम संकेत",
    "Receipt completed. The one-time QR is no longer active; inspect the passport timeline for evidence." to "पावती पूर्ण झाली. एकदाच वापरता येणारा QR आता सक्रिय नाही; पुराव्यासाठी पासपोर्ट टाइमलाइन तपासा.",
    "Review formal settlement" to "औपचारिक सेटलमेंट तपासा",
    "Accept settlement" to "सेटलमेंट स्वीकारा",
    "Try detection again" to "पुन्हा फोटो तपासा",
    "Loading scrap photos…" to "स्क्रॅप फोटो लोड होत आहेत…",
    "Some photos could not be processed. Please choose a JPEG, PNG, or WebP image." to "काही फोटो प्रक्रिया करता आले नाहीत. JPEG, PNG किंवा WebP इमेज निवडा.",
    "angles available" to "अँगल उपलब्ध",
    "angle available" to "अँगल उपलब्ध",
    "Retry" to "पुन्हा प्रयत्न करा",
    "Refresh" to "रिफ्रेश करा",
    "Pending inspection" to "तपासणी प्रलंबित",
    " kg" to " किलो"
)
